#include <stdio.h>
#include <string.h>
#include <math.h>

#define A 100
#define B 100

/**
 * Only numbers that may produce the same values are those that can be
 * expressed as powers of the same prime factors
 */

int main(){
    printf("29. How many distinct terms are in the sequence generated by \
a^b for 2 <= a <= 100 and 2 <= b <= 100?\n");

    int i, j, n, count = 0, occurr[A + 1] = {0}, power[601];

	for (i = 2; i <= A; ++i){
        memset(power, 0, sizeof *power * 601);

        if(!occurr[i]) //if the base hasn't yet occurred

            for(j = i; j <= A; j *= i){
                occurr[j] = 1;

                int exp = log(j) / log(i);
                for(n = 2; n <= B; n++)
                    if(!power[n * exp]){
                        power[n * exp] = 1;
                        count++;
                    }
            }
    }
    printf("There are %d distinct terms.\n", count);
    return 0;
}